version: "3.8"

services:
  kafka-logger:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka-logger
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_NUM_PARTITIONS: 2
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      KAFKA_CLIENT_LISTENER_NAME: ${KAFKA_CLIENT_LISTENER_NAME}
    networks:
      - logger
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami

  logger:
    restart: unless-stopped
    container_name: logger
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
    depends_on:
      - kafka-logger
    networks:
      - logger
    ports:
      - "3009:3009"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  logger:
    driver: bridge
