version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.6
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  logger:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logger
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
    depends_on:
      - zookeeper
      - kafka
    networks:
      - backend
    ports:
      - "3009:3009"
    volumes:
      - .:/logger

networks:
  backend:
    driver: bridge
