openapi: 3.0.0
info:
  title: Microservicio Logger
  version: 1.0.0
  description: Logger for medical consultation application. Saves and handles all the logs from the different microservices 

servers:
  - url: http://localhost:3001

paths:
  # Aquí irán tus rutas

components:
  # Aquí irán tus componentes reutilizables
