apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-logger
  name: kafka-logger
spec:
  type: LoadBalancer
  ports:
    - name: "internal"
      port: 9092
      targetPort: 9092
    - name: "external"
      port: 30092
      targetPort: 30092
      nodePort: 30092
  selector:
    io.kompose.service: kafka-logger
