apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-logger
  name: kafka-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-logger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka-logger
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CFG_ADVERTISED_LISTENERS
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 1@127.0.0.1:9093
            - name: KAFKA_CFG_LISTENERS
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CFG_LISTENERS
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_CLIENT_LISTENER_NAME
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CLIENT_LISTENER_NAME
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                secretKeyRef:
                  name: logger-secrets
                  key: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_NUM_PARTITIONS
              value: "2"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: broker,controller
          image: docker.io/bitnami/kafka:3.9
          name: kafka-logger
          livenessProbe:
            exec:
              command:
              - kafka-topics.sh
              - --list
              - --bootstrap-server
              - localhost:9092
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9094
              protocol: TCP
          volumeMounts:
            - mountPath: /bitnami
              name: kafka-data
      restartPolicy: Always
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
